name: envs
dependencies:
  - python=3.10.11
  - pip
  - pip:
    - gymnasium
    - pybullet
    - matplotlib
    - opencv-python
    - pygame
    - numpy
    - tqdm
    - pandas
    - h5py
    - tensorflow<2.11